# เลือกภาพ Docker ที่ใช้งาน Go
FROM golang:latest

# สร้างโฟลเดอร์ใหม่สำหรับโปรเจกต์
RUN mkdir /app
ADD . /app
WORKDIR /app

# ติดตั้ง Gin และการตั้งค่าโปรเจกต์ Go Gin
RUN go get -u github.com/gin-gonic/gin

# เปิดพอร์ตที่เซิร์ฟเวอร์ Go Gin จะใช้


# Build และ Run เซิร์ฟเวอร์ Go Gin
CMD ["go", "run", "app.go"]
